docs: Add issue template
bank-vaults/bank-vaults.dev pull request #155
Opened 2023-08-03 05:24 UTC by tanmay-pnaik

## Overview

Add issue template

## Notes for reviewer

Adapted from https://github.com/bank-vaults/vault-operator/tree/main/.github/ISSUE_TEMPLATE

2023-11-18 08:29 UTC, fekete-robert commented on .github/ISSUE_TEMPLATE/bug_report.yaml
> +        If you are not sure if it is a bug or not, you can contact us via the available [support channels](https://github.com/bank-vaults/bank-vaults.dev/issues/new/choose).
https://github.com/bank-vaults/bank-vaults.dev/pull/182/ will restore the support page, so we can update this link and merge this PR after PR#1882

2023-11-22 15:51 UTC, ramizpolic requested changes

2023-11-22 15:51 UTC, ramizpolic commented on .github/ISSUE_TEMPLATE/bug_report.yaml
> +        If you are not sure if it is a bug or not, you can contact us via the available [support channels](https://github.com/bank-vaults/bank-vaults.dev/issues/new/choose).
The new link is: https://bank-vaults.dev/docs/support/

2023-11-22 15:51 UTC, ramizpolic commented on .github/ISSUE_TEMPLATE/feature_request.yaml
> +description: Suggest an idea for the Bank-Vaults Documentation
```suggestion
description: Suggest an idea for the Bank-Vaults Documentation
labels: [kind/enhancement]
```

2023-11-22 15:51 UTC, ramizpolic commented on .github/ISSUE_TEMPLATE/feature_request.yaml
> +        If you are not sure if your request fits into Dex, you can contact us via the available [support channels](https://github.com/bank-vaults/vault-operator/issues/new/choose).
```suggestion
        If you are not sure if your request fits into Dex, you can contact us via the available [support channels](https://bank-vaults.dev/docs/support).
```

2023-11-22 15:51 UTC, ramizpolic commented on .github/ISSUE_TEMPLATE/feature_request.yaml
> +        - label: I have searched the [issue tracker](https://www.github.com/bank-vaults/vault-operator/issues) for an issue that matches the one I want to file, without success.
```suggestion
        - label: I have searched the [issue tracker](https://www.github.com/bank-vaults/bank-vaults.dev/issues) for an issue that matches the one I want to file, without success.
```

2023-11-23 11:35 UTC, tanmay-pnaik commented on .github/ISSUE_TEMPLATE/bug_report.yaml
> +        If you are not sure if it is a bug or not, you can contact us via the available [support channels](https://github.com/bank-vaults/bank-vaults.dev/issues/new/choose).
Thanks!

2023-11-23 11:35 UTC, tanmay-pnaik commented on .github/ISSUE_TEMPLATE/feature_request.yaml
> +description: Suggest an idea for the Bank-Vaults Documentation
Fixed!

2023-11-23 11:35 UTC, tanmay-pnaik commented on .github/ISSUE_TEMPLATE/feature_request.yaml
> +        If you are not sure if your request fits into Dex, you can contact us via the available [support channels](https://github.com/bank-vaults/vault-operator/issues/new/choose).
Fixed!

2023-11-23 11:36 UTC, tanmay-pnaik commented on .github/ISSUE_TEMPLATE/feature_request.yaml
> +        - label: I have searched the [issue tracker](https://www.github.com/bank-vaults/vault-operator/issues) for an issue that matches the one I want to file, without success.
Fixed!

2023-11-23 11:40 UTC, ramizpolic approved these changes
Much appreciated, @tanmay-pnaik!

2023-11-23 11:40 UTC, merged