v1.20.0 upgrade guide
bank-vaults/bank-vaults.dev pull request #189
Opened 2023-11-24 15:10 UTC by akijakya

## Overview

Fixes #107

## Notes for reviewer

<img width="1453" alt="Screenshot 2023-11-24 at 16 08 15" src="https://github.com/bank-vaults/bank-vaults.dev/assets/39521244/fb6725ff-509c-4b40-9d71-08ab0664ea95">

2023-11-27 14:57 UTC, fekete-robert approved these changes

2023-11-27 14:57 UTC, fekete-robert commented on content/docs/operator/upgrade.md
> +### v1.20.0 upgrade guide
```suggestion
## v1.20.0 upgrade guide
```

2023-11-28 08:36 UTC, ramizpolic requested changes
Sorry for the confusion with the upgrade strategies. I have added items to address two scenarios: upgrading Vault, and upgrading Operator.

2023-11-28 08:36 UTC, ramizpolic commented on content/docs/operator/upgrade.md
> +title: Upgrade Vault operator
```suggestion
title: Upgrade strategies
```

2023-11-28 08:36 UTC, ramizpolic commented on content/docs/operator/upgrade.md
> +To upgrade the Vault operator, complete the following steps.
```suggestion
## Upgrade Vault

To upgrade the Vault, complete the following steps.
```

2023-11-28 08:36 UTC, ramizpolic commented on content/docs/operator/upgrade.md
> +1. The Bank-Vaults operator (or the Vault Helm chart) updates the StatefulSet. (It does not take the HA leader into account in HA scenarios, but this has never caused any issues so far.)
```suggestion
1. The Vault Helm chart updates the StatefulSet. It does not take the HA leader into account in HA scenarios, but this has never caused any issues so far.
```

2023-11-28 08:36 UTC, ramizpolic commented on content/docs/operator/upgrade.md
> +## v1.20.0 upgrade guide
```suggestion
## Upgrade Vault operator

### v1.20.0 upgrade guide
```

2023-11-28 08:36 UTC, ramizpolic commented
We can merge once these items are resolved and DCO passing.

2023-11-28 12:21 UTC, ramizpolic approved these changes

2023-11-28 12:21 UTC, merged